-- INSERT INTO item(item_level, name, item_slot) VALUES(410, 'Colossal Dragonplate Helmet', 'HEAD');
-- INSERT INTO stat(key, value, item_id) VALUES('STRENGTH', 489, 1);
-- INSERT INTO stat(key, value, item_id) VALUES('STAMINA', 824, 1);
-- INSERT INTO gem_slot(color, item_id) VALUES('META', 1);
-- INSERT INTO gem_slot(color, item_id) VALUES('RED', 1);