package items.Enums;

public enum StatsEnum {
    ARMOR,
    STRENGTH,
    AGILITY,
    INTELLECT,
    STAMINA,
    SPIRIT,
    EXPERTISERATING,
    HITRATING,
    CRITRATING,
    MASTERYRATING,
    HASTERATING,
    ATTACKPOWER,
    SPELLPOWER
}